# --- Toolchain & Hardware Settings ---
MCU = 16F877A
CC = xc8-cc
DFP_PATH = "C:/Users/Ziad/Desktop/Academic/College zewail city/Courses/CIE/Year 4/CIE 408 Embedded Systems/Compiler/Microchip.PIC16Fxxx_DFP.1.7.162/xc8"

# Toolchain flags
CFLAGS = -mcpu=$(MCU) -Os -mdfp=$(DFP_PATH)

# --- Include Directories ---
# This still saves you from writing "../" in your C files, 
# but it does NOT compile anything automatically.
INCLUDES = -I. \
           -IMCAL/MCAL_GPIO \
           -IMCAL/MCAL_UART \
           -IMCAL/MCAL_interrupt \
           -IHAL/HAL_IR \
           -IHAL/HAL_LCD \
           -ISERVICES 

# --- Explicit Source Files ---
# EXACTLY what the compiler will look at. 
# If you add a new driver, you MUST add its .c file here.
SRCS = APP/main.c \
       MCAL/MCAL_GPIO/GPIO.c \
       MCAL/MCAL_interrupt/interrupt.c \
       MCAL/MCAL_UART/UART.c \
       HAL/HAL_IR/HAL_IR.c \
       HAL/HAL_LCD/HAL_LCD.c 

# --- Output Name ---
TARGET = build/test.hex

all: build $(TARGET)

# --- Compilation and Linking Stage ---
$(TARGET): $(SRCS) 
	$(CC) $(CFLAGS) $(INCLUDES) $(SRCS) -o $(TARGET)


clean:
	-@del /Q /F build\*.elf build\*.cmf build\*.hxl build\*.sym build\*.sdb build\*.o build\*.p1 build\*.d build\*.s build\*.lst build\*.rlf build\__eeprom.* 2>nul